export const predefinedPerks = [
    { id: '1', title: 'Give your fans downloadable digital goods' },
    { id: '2', title: 'Early ticket access' },
    { id: '3', title: 'Offer premium or early access tickets for live events' },
    { id: '4', title: 'Digital ebook or publication' },
    { id: '5', title: 'Early access' },
    { id: '6', title: 'Live event VIP' },
    { id: '7', title: 'Exclusive content' },
    { id: '8', title: 'Fan requests' },
    { id: '9', title: 'Live chat' },
    { id: '10', title: 'Live Q&As' },
    { id: '11', title: 'Livestreams' },
    { id: '12', title: 'Merch' },
    { id: '13', title: 'Member shout-out' },
    { id: '14', title: 'Phone call' },
    { id: '15', title: 'Complete post archive' },
    { id: '16', title: 'Private community' },
    { id: '17', title: 'Promo code' },
    { id: '18', title: 'Video tutorials & lessons' },
    { id: '19', title: 'Exclusive voting power' },
    { id: '20', title: 'Work-in-progress updates (digital)' },
    { id: '21', title: 'Work-in-progress updates (delivered by mail)' },
    { id: '22', title: 'Discord Server Access' },
    { id: '23', title: '1-on-1 Mentorship' },
    { id: '24', title: 'Behind-the-scenes content' },
];
