export const predefinedPerks = [
    { id: '7', title: 'Video tutorials & lessons' },
    { id: '4', title: '1-on-1 Mentorship' },
    { id: '5', title: 'One-on-one consultation/guidance session' },
    { id: '10', title: 'Live Q&As' },
    { id: '6', title: 'Course/lesson library access' },
    { id: '3', title: 'Voice note reply' },
    { id: '13', title: 'Phone call' },
    { id: '8', title: 'Private discussion group' },
    { id: '9', title: 'Direct Q&A on current events' },
    { id: '11', title: 'Member shout-out' },
    { id: '12', title: 'Birthday/anniversary shoutout' },
    { id: '14', title: 'Behind-the-scenes content' },
    { id: '2', title: 'Personal dua/prayer request' },
    { id: '15', title: 'Certificate of completion' },
    { id: '16', title: 'Exclusive content' },
    { id: '17', title: 'Resource/template downloads' },
    { id: '18', title: 'Livestreams' },
    { id: '1', title: 'WhatsApp/Telegram Group Access' },
    { id: '19', title: 'Priority reply' },
    { id: '20', title: 'Live chat' },
    { id: '21', title: 'Give your fans downloadable digital goods' },
    { id: '22', title: 'Early access' },
    { id: '23', title: 'Ad-free experience' },
    { id: '24', title: 'Merch' },
    { id: '25', title: 'Custom badge / supporter tag' },
    { id: '26', title: 'Private community' },
    { id: '27', title: 'Fan requests' },
    { id: '28', title: 'Play with the creator' },
    { id: '29', title: 'Uncensored/unfiltered takes' },
    { id: '30', title: 'Early access to gameplay/builds' },
    { id: '31', title: 'Discord Server Access' },
    { id: '32', title: 'Promo code' },
    { id: '33', title: 'Digital ebook or publication' },
    { id: '34', title: 'Monthly group call' },
    { id: '35', title: 'Exclusive voting power' },
    { id: '36', title: 'Work-in-progress updates (digital)' },
    { id: '37', title: 'Custom game name/tag shoutout' },
    { id: '38', title: 'Vote on next game/content' },
    { id: '39', title: 'Physical signed item' },
    { id: '40', title: 'Pre-recorded analysis before public release' },
    { id: '41', title: 'Complete post archive' },
    { id: '42', title: 'Early ticket access' },
    { id: '43', title: 'Offer premium or early access tickets for live events' },
    { id: '44', title: 'Live event VIP' },
    { id: '45', title: 'Work-in-progress updates (delivered by mail)' },
];
